name:         JavaScript-SpiderMonkey
version:      0.23
version_from: SpiderMonkey.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Log::Log4perl:                 0
resources:
  repository: https://github.com/thomasbusch/perl-javascript-spidermonkey.git

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
